import { TVChannel, TVProgram } from '../types/tv';

export const CHANNELS: TVChannel[] = [
  { number: 1, name: 'NHK General', shortName: 'NHK G', isFuji: false, frequency: '473.14MHz' },
  { number: 2, name: 'NHK Educational', shortName: 'NHK E', isFuji: false, frequency: '479.14MHz' },
  { number: 3, name: 'Independent Network', shortName: 'IND', isFuji: false, frequency: '485.14MHz' },
  { number: 4, name: 'Nippon TV (NTV)', shortName: 'NTV', isFuji: false, frequency: '491.14MHz' },
  { number: 5, name: 'TV Asahi', shortName: 'EX', isFuji: false, frequency: '497.14MHz' },
  { number: 6, name: 'TBS Television', shortName: 'TBS', isFuji: false, frequency: '503.14MHz' },
  { number: 7, name: 'TV Tokyo', shortName: 'TX', isFuji: false, frequency: '509.14MHz' },
  { number: 8, name: 'Fuji Television (CX)', shortName: 'FUJI TV', isFuji: true, frequency: '515.14MHz' },
  { number: 9, name: 'TOKYO MX', shortName: 'MX', isFuji: false, frequency: '521.14MHz' },
  { number: 10, name: 'Television Saitama', shortName: 'TVS', isFuji: false, frequency: '527.14MHz' },
  { number: 11, name: 'J:COM Channel', shortName: 'J:COM', isFuji: false, frequency: '533.14MHz' },
  { number: 12, name: 'Open University', shortName: 'OUJ', isFuji: false, frequency: '539.14MHz' },
];

export const FUJI_PROGRAMS: TVProgram[] = [
  {
    id: 'fuji-mezamashi',
    channelNumber: 8,
    title: 'Mezamashi TV (Morning News & Entertainment)',
    genre: 'News & Morning Magazine',
    timeSlot: '05:25 - 08:00',
    description: 'Japan’s premier morning news show broadcasting live from Fuji TV Headquarters in Odaiba, Tokyo. Features live weather, entertainment headlines, and the interactive Mezamashi Janken game.',
    cast: ['Masaharu Miyake', 'Seika Inoue', 'Ryusei Ikuta', 'Mezamashi-kun'],
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  {
    id: 'fuji-pokapoka',
    channelNumber: 8,
    title: 'Poka Poka (Live Midday Variety)',
    genre: 'Variety & Entertainment',
    timeSlot: '11:50 - 13:50',
    description: 'Energetic live lunchtime variety program broadcasting daily from Fuji TV Studio Promenade with live viewer interactive voting.',
    cast: ['Haraichi (Iwai & Sawabe)', 'Aika Kanda'],
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  {
    id: 'fuji-onepiece',
    channelNumber: 8,
    title: 'ONE PIECE (Egghead Island Arc)',
    genre: 'Anime & Action',
    timeSlot: '09:30 - 10:00',
    description: 'The global anime phenomenon on Fuji TV! Luffy and the Straw Hat Pirates navigate the futuristic mysteries of Egghead Island against the World Government.',
    cast: ['Mayumi Tanaka', 'Kazuya Nakai', 'Akemi Okamura', 'Kappei Yamaguchi'],
    hasSubtitles: true,
    hasBilingual: true,
    hasDataBroadcast: true,
  },
  {
    id: 'fuji-sazae',
    channelNumber: 8,
    title: 'Sazae-san (Iconic Family Classic)',
    genre: 'Anime & Family',
    timeSlot: '18:30 - 19:00',
    description: 'Guinness World Record holder for the longest-running animated TV series. A Sunday evening tradition across Japanese households followed by the famous Janken battle.',
    cast: ['Midori Kato', 'Hideyuki Tanaka', 'Miina Tominaga'],
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  {
    id: 'fuji-drama',
    channelNumber: 8,
    title: 'Getsu 9 Prime Drama Special',
    genre: 'Romance & Drama',
    timeSlot: '21:00 - 21:54',
    description: 'Fuji TV’s legendary Monday 9 PM golden drama slot. An emotional cinematic romance featuring star-studded casts set against Tokyo coastal horizons.',
    cast: ['Nana Mori', 'Shotaro Mamiya', 'Fuju Kamio', 'Ai Yoshikawa'],
    hasSubtitles: true,
    hasBilingual: true,
    hasDataBroadcast: true,
  },
  {
    id: 'fuji-sports',
    channelNumber: 8,
    title: 'Fuji TV Sports: Pro Baseball Live',
    genre: 'Sports & Live Action',
    timeSlot: '19:00 - 20:54',
    description: 'Exclusive live broadcast from Meiji Jingu Stadium. Interactive d-data tracking pitch speeds, strike zones, and player statistics in real time.',
    cast: ['Atsuya Furuta (Analyst)', 'Motonobu Tanishige (Analyst)', 'Mitsuhiro Nakamura'],
    hasSubtitles: true,
    hasBilingual: true,
    hasDataBroadcast: true,
  },
  {
    id: 'fuji-fnn',
    channelNumber: 8,
    title: 'FNN Live News α (Nightly Business)',
    genre: 'News & Global Markets',
    timeSlot: '23:40 - 00:25',
    description: 'Comprehensive late-night broadcast analyzing financial markets, AI technology innovations, and international economic trends.',
    cast: ['Reimi Tsutsumi', 'Yuka Ebihara'],
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
];

export const OTHER_CHANNEL_PROGRAMS: Record<number, TVProgram> = {
  1: {
    id: 'nhk-g-news',
    channelNumber: 1,
    title: 'NHK News 7',
    genre: 'National News',
    timeSlot: '19:00 - 19:30',
    description: 'Authoritative national and international news coverage from Japan’s public broadcaster.',
    hasSubtitles: true,
    hasBilingual: true,
    hasDataBroadcast: true,
  },
  2: {
    id: 'nhk-e-kids',
    channelNumber: 2,
    title: 'PythagoraSwitch',
    genre: 'Educational',
    timeSlot: '18:40 - 18:50',
    description: 'Award-winning educational showcase featuring ingenious Rube Goldberg mechanics and problem solving.',
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: false,
  },
  4: {
    id: 'ntv-variety',
    channelNumber: 4,
    title: 'Itte Q! (Expedition to the Ends of the Earth)',
    genre: 'Adventure Variety',
    timeSlot: '19:58 - 20:54',
    description: 'Hilarious global expeditions and survival challenges across diverse continents.',
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  5: {
    id: 'ex-music',
    channelNumber: 5,
    title: 'Music Station Live',
    genre: 'Music & Performance',
    timeSlot: '21:00 - 21:54',
    description: 'Live studio performances featuring top international and J-pop musical artists.',
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  6: {
    id: 'tbs-drama',
    channelNumber: 6,
    title: 'Sunday Theatre',
    genre: 'Prime Drama',
    timeSlot: '21:00 - 21:54',
    description: 'High-budget corporate and suspense drama productions.',
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  7: {
    id: 'tx-wbs',
    channelNumber: 7,
    title: 'World Business Satellite (WBS)',
    genre: 'Business & Tech',
    timeSlot: '22:00 - 22:58',
    description: 'Prime business insights and startup showcase.',
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: true,
  },
  9: {
    id: 'mx-anime',
    channelNumber: 9,
    title: 'TOKYO MX Late Night Anime Block',
    genre: 'Anime Premiere',
    timeSlot: '23:00 - 23:30',
    description: 'Simulcast premiere episodes from acclaimed animation studios.',
    hasSubtitles: true,
    hasBilingual: false,
    hasDataBroadcast: false,
  },
};

export const ODAIBA_WEATHER = {
  city: 'Tokyo, Minato Ward, Odaiba (Fuji TV HQ)',
  temp: '22°C (71.6°F)',
  condition: 'Clear to Sunny',
  rainChance: '10%',
  humidity: '58%',
  wind: 'SSW 3.2 m/s',
  hachitamaObservation: 'Hachitama Spherical Observatory: High visibility, Mt. Fuji visible across Tokyo Bay',
};

export const FUJI_NEWS_TICKER = [
  '[BREAKING] Fuji Television anniversary gala broadcast begins tonight live from Odaiba Studio',
  '[MEZAMASHI] Double points event on tomorrow morning’s Mezamashi Janken game session',
  '[FOD STREAMING] New blockbuster drama series and anime specials now streaming on demand',
  '[ODAIBA] Special architectural tour open at Fuji TV Headquarters Spherical Observatory Hachitama',
];
